### ISSUE TITLE
kickstart /usr/sbin/mkefiboot fails

### ISSUE THREAD

**Issue by r351574nc3** [dracutdevs/dracut#341]
I am trying to reuse a `fedora-live-base.ks` to create a livecd image. I have the following in my `.ks` file in order to add initramfs to my livecd.

```
# Without this, initramfs generation during live image creation fails: #1242586
dracut-live
grub2-efi
syslinux
```

However, in the process of creating the initramfs, the following happens. Looks like it's actually part of lorax, but I wonder if it is how dracut is being used or if you know a workaround.

Traceback (most recent call last):
  File "/usr/sbin/mkefiboot", line 167, in <module>
    main()
  File "/usr/sbin/mkefiboot", line 158, in main
    opt.diskname)
  File "/usr/sbin/mkefiboot", line 45, in mkmacboot
    mkhfsimg(None, outfile, label=label, graft=graft, size=size)
  File "/usr/lib/python3.6/site-packages/pylorax/imgutils.py", line 479, in mkhfsimg
    mkfsargs=["-v", label], graft=graft)
  File "/usr/lib/python3.6/site-packages/pylorax/imgutils.py", line 452, in mkfsimage
    with Mount(loopdev, mountargs) as mnt:
  File "/usr/lib/python3.6/site-packages/pylorax/imgutils.py", line 343, in __enter__
    self.mnt = mount(self.dev, self.opts, self.mnt)
  File "/usr/lib/python3.6/site-packages/pylorax/imgutils.py", line 226, in mount
    runcmd(cmd)
  File "/usr/lib/python3.6/site-packages/pylorax/executils.py", line 341, in runcmd
    return execWithRedirect(cmd[0], cmd[1:], **kwargs)
  File "/usr/lib/python3.6/site-packages/pylorax/executils.py", line 228, in execWithRedirect
    env_add=env_add, reset_handlers=reset_handlers, reset_lang=reset_lang)[0]
  File "/usr/lib/python3.6/site-packages/pylorax/executils.py", line 201, in _run_program
    raise subprocess.CalledProcessError(proc.returncode, argv, output)
subprocess.CalledProcessError: Command '['mount', '/dev/loop1', '/tmp/lorax.imgutils.zi2y1368']' returned non-zero exit status 32.

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.
